# Naive Bayes (Multinomial NB) Spam Detection

In [1]:
# Load Libraries

import pandas as pd
import numpy as np

In [6]:
dataset=pd.read_csv("S:/Evacity Course/Datasets/Spam Data/spam.csv", encoding='latin-1')

In [10]:
dataset.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [11]:
dataset.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [12]:
dataset.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
dataset['spam']=dataset['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [16]:
dataset.head()

v1                                                 v2  spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset['v2'], dataset['spam'], test_size=0.3, random_state=42)

In [54]:
X_train_count=vector.fit_transform(X_train.values)

In [59]:
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [62]:
nb.fit(X_train_count, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [64]:
email=[
    'Mohan come lets play',
    'upto 50% discount'
]

In [65]:
email_count=vector.transform(email)

In [66]:
nb.predict(email_count)

array([0, 1], dtype=int64)

In [68]:
x_test_count=vector.transform(X_test)

In [70]:
nb.score(x_test_count, y_test)

0.9820574162679426

In [72]:
# Pipeline Method

from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer', CountVectorizer()),
             ('nb', MultinomialNB())])

In [73]:
clf.fit(X_train, y_train)


Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [74]:
clf.score(X_test, y_test)

0.9820574162679426

In [75]:
clf.predict(email)

array([0, 1], dtype=int64)